---
- name: Check for Postgres Network
  shell: docker network ls
  register: docker_network_ls

- name: Check for Containers
  shell: docker container ls
  register: docker_container_ls

- name: Create Docker Network
  shell: docker network create postgres
  when: docker_network_ls.stdout is search('postgres') == False

- name: Create Postgres Container
  shell: >
    docker run --name postgres \
    -e "POSTGRES_PASSWORD={{ postgres_password }}" \
    --network postgres \
    -d postgres
  when: docker_container_ls.stdout is search('postgres') == False

- name: Create PGAdmin4 Container
  shell: >
    docker run --name pgadmin4 \
    -p 5433:80 \
    -e "PGADMIN_DEFAULT_EMAIL={{ pgadmin_default_email }}" \
    -e "PGADMIN_DEFAULT_PASSWORD={{ pgadmin_default_password }}" \
    --network postgres \
    -d dpage/pgadmin4
  when: docker_container_ls.stdout is search('pgadmin4') == False
